### ISSUE TITLE
Rename `\avoidAnnBreak` / `\letAnnBreak` ?

### ISSUE THREAD

**Issue by uliska** [openlilylib/scholarly#15]
`\avoidAnnBreak` and `\letAnnBreak` seem to be very useful functions and seem to work as intended.

However, on first thought: may I _suggest_ a different approach to naming (in general)? Going from general to specific by giving _all_ commands the same prefix (e.g. `scholarly` or `ann`), following that by the _category/function_ and ending with an indicator of the _value_. So that would for example suggest `\annBreakAvoid` / `\annBreakAllow`. Or something similar. I have the _impression_ that would make things more apparent for users.

**Comment by jefferyshivers** [comment]
`\annBreakAvoid` and `\annBreakAllow` are the commands now, with the default behavior being to _avoid_ breaks.
