### ISSUE TITLE
\verboseMeasures and \verboseBeats

### ISSUE THREAD

**Issue by uliska** [openlilylib/scholarly#16]
What are `\verboseMeasures` and `\verboseBeats` supposed to do? I can't see any difference when using them in the `\setcustomdraft` context.

**Comment by jefferyshivers** [comment]
If they are set within \setcustomdraft or \setcustomfinal, then \usecustomdraft (or final), which is the toggle for implementing custom draft or default draft) must be set afterwards, and the mode must also be draft. I did a lot of testing with that one (verbose) and am sure it works now, though I haven't given a good explanation of it I admit.

When set properly, verbose measures (and/or beats) will always show the respective number for the annotation, even when the same measure occurs two annotations in succession. However, the default behavior (when verbose is not turned on), is to replaced the measure/beat number, if repeated, with a stub. The default for that is `---`for both measures and beats, but either/both can be changed by the user. Of course, repeated beats only count as repeated if the measure is also repeated. So m.3, b.4 followed by m.5, b.4 would _not_ treat the second beat 4 as a repetition.

In the example doc, there isn't repetition of location between the two annotations, so this isn't appreciated. I will add an additional annotation that can employ this toggle. I'm open to coming up with other ways of setting toggles like these and hide/show types, and maybe toggles to use/not-use other additional features, but the number of how many things will be toggled is so undetermined at the moment, this is just the blandest/_cheapest_ way to make sure it at least exists initially.

**Comment by uliska** [comment]
OK, that makes sense. I'll wait until your current round of commits is over and give it another look then.

Probably here's another spot for a rename, as I obviously was misled by the term `verbose`.

**Comment by jefferyshivers** [comment]
Another thought about this - should the default behavior be the reverse? Then default would be to always show mm. and beat numbers, and _optionally_ have repeated ones "turned off" (or rather, abbreviated by the --- or whatever the user puts).

**Comment by jefferyshivers** [comment]
It should probably also be a third option to _only_ hide repeated locations when it is the exact same location (i.e. measure and beat (and any further subdivision) are collectively the same as in last annotation).

**Comment by uliska** [comment]
> Then default would be to always show mm. and beat numbers, and optionally have repeated ones "turned off" 

I don't have a strong opinion about this, but maybe your suggested reverse would be less surprising and thus better suited as a default.

> It should probably also be a third option to only hide repeated locations when it is the exact same location

Yes, I think this is a good suggestion.

**Comment by jefferyshivers** [comment]
This will have to be reworked slightly to account rhythmic divisions smaller than beats as well. But the whole way of gathering that information is itself going need to shift soon, since currently the rhythmic locations are still entirely obtained from 2nd and 3rd arguments in the inp export.

**Comment by jefferyshivers** [comment]
Now the default behavior is to show all locations. The options are:

```
\annSameLocationShow % shows all (the default)
\annSameLocationStrict % only hide when exactly same location as previous ann
\annSameLocationLoose % hide both if both same as previous, or hide measure if same (never just beat)
```

They can be called anytime in the doc to change the behavior. `annotate.tex` does this for the second example.
