### ISSUE TITLE
Confusing output with draft/final and \hideAnnType

### ISSUE THREAD

**Issue by uliska** [openlilylib/scholarly#17]
I am somewhat confused about the behaviour of `\hideAnnType`.

Actually I can _only_ get the annotation type to print with the combination of `draft` and `\finalforcustom`. With every other combination it isn't printed.

**Comment by jefferyshivers** [comment]
Final mode by default hides type, and draft mode by default shows it. \hideAnnType (which is being renamed) will always hide type no matter what mode, as long as it is outside of a \setcustom... field, and until it is reset by \showAnnType (and vice versa). These will stay in effect until reset.

The current example tex doc is admittedly exaggerated/clogged with settings toggled on/off, in/out of fields constantly, but I'm testing this feature right now and it works. If you trim the file down it should be more obvious when it is working. The next example update will do a better job of demonstrating this, and will itself be cut down for clarity.

**Comment by jefferyshivers** [comment]
Maybe custom should be a third option, actually? So the configurations would be:

```
\usepackage{scholarLY}% if not set, then default final
\usepackage[final]{scholarLY}% default final
\usepackage[draft]{scholarLY}% default draft
\usepackage[final, custom]{scholarLY}% custom final (or "custom final" instead of "final, custom"?)
\usepackage[draft, custom]{scholarLY}% custom draft (same as above?)
```

**Comment by uliska** [comment]
> Final mode by default hides type, and draft mode by default shows it. \hideAnnType (which is being renamed) will always hide type no matter what mode, as long as it is outside of a \setcustom... field, and until it is reset by \showAnnType (and vice versa). These will stay in effect until reset.

OK, this wasn't clear from the example file. I thought commenting in/out `\hideAnnType` is the expected behaviour, but now I see that I have to add `\showAnnType` to the `\setcustomfinal`. Now that works. as it should.

> Maybe custom should be a third option, actually? 

Yes, I think that makes sense and reduces some complexity from the package configuration (well, not _really_, but it's done in a more obvious place).

However, I would suggest to make the `custom` option the default (that is, when a `\setcustomXXX` is present use it) and have the option `nocustom` instead.

**Comment by jefferyshivers** [comment]
1c9528c2cef3fccb70a20eaf2aa6cbcf5a9dac7b makes custom settings the default.

```
`\annSetDraft{
    \setkeys{annStyles}{...}
    \annInline
    % etc.
}
```

The package options are now `draft` `final`(implicit), `nocustom`, and `custom`(implicit).
