### ISSUE TITLE
Naming of styling commands

### ISSUE THREAD

**Issue by uliska** [openlilylib/scholarly#18]
Similar to #15 I suggest reconsidering the naming of the commands to style the annotation display:

My suggestion:
- `\annStyleType`
- `\annHideType` (not `Types`)
- `\annStyleMessage`
- `\annStackedParams`
- `\annVerboseMeasures`
- `\annVerboseBeats`

**Comment by jefferyshivers** [comment]
Okay, this makes sense. I'm doing a _naming_ overhaul of the package right now.
