### ISSUE TITLE
Configuring "message" appearance

### ISSUE THREAD

**Issue by uliska** [openlilylib/scholarly#19]
I have some issues with the way the appearance of the message is fine-tuned. Actually it's two different questions that are somewhat interdependent.
##### A) Naming

Similar to #15 and #18 I'd like to question the naming of `\setPreMessFirst` and the other functions that define the appearance of the actual message. In order to make the commands consistent with what I suggest they start with `\annMessage` each.

But:
##### B) Approach

I think this could be made more concise through one out of several approaches:
- Just leave them all away, as everything _can_ be achieved within `\styleAnnMessage`
- Reduce the number of commands by using one command for left and right, like  
  `\newcommand{\annMessageWrap}[2][]{...}` with an optional argument. When that's not set right and left will be the same. (And another command for the outer wrap)
- Create _one_ command and do all the configuration with keyval arguments.

**Comment by jefferyshivers** [comment]
How about `\annMessageWrap{"/"}`, which interprets anything _before_ the `/` as left, and _after_ as right?

So `\annMessageWrap{/"}` would only apply to the right, `...{"/}` only to the left, `...{"/*}` to their respective places, and `...{"}` implicitly to both.

**Comment by jefferyshivers** [comment]
And then the same syntax for the outer wrap. Which could be named.. `\annMessageWrapOuter{...}`? It's a mouthful though. Maybe `\annMessageWrapOut`?

**Comment by uliska** [comment]
If you're confident that `/` is a suitable character for this I agree with the idea. But there should still be a way to use the separator character as an actual wrapping character. I don't know how simple it is to simply have that escaped so that writing `\annMessageWrap{\/ / \/}` would wrap the message in two slashes with inner space. 

However, that remark doesn't really affect the choice of the character because I can't think of any character that no one will ever want to use as a wrapper. If my suggestion with the backslash escape doesn't work one could still add something like `\annMessageWrapSep` or similar.

**Comment by jefferyshivers** [comment]
For `\annMessageWrap{ (left wrap) / (right wrap)`, `annMessageWrapOuter{ .. / .. }` and `annTypeWrap{ .. / .. }`, the separator `/` is now just the default, and can be redefined with `\annMessageWrapSep{(new separator)`, `annMessageOuterWrapSep{ .. }` and `annTypeWrapSep{ .. }` from caf43724f05c980ed34432d07dfb6f66a4fd0562
