### ISSUE TITLE
Configuring field prefixes

### ISSUE THREAD

**Issue by uliska** [openlilylib/scholarly#20]
Maybe this is due to the temporary nature of the file, but I feel the `\def\lygrobPfx` syntax to be somewhat inconsistent. These should maybe get "LaTeX-like" wrapper commands - or rather _one_ wrapper command with keyval options for the individual fields.

**Comment by jefferyshivers** [comment]
Okay, I agree keyval is a better way to set those. How should the families be grouped?
I am thinking at least annStyles and annPrefixes, and then there needs to be at least one more for the rest of the keyval options which don't fit into those two (though some, like verbose beats, etc., should probably remain as macros). So the user would

```
\setkeys{annStyles}{%
    message = {\color{cyan}##1},
    measure = {\textbf{##1}}
}
\setKeys{annPrefixes}{%
    measure = {M. }
}
\setKeys{annExtras}{% though maybe a more tasteful name
    measure-same = {---)% displayed for measures repeated, unless `verbose measure` is turned on
)
```

Or, do you think annMessage, annType, annLocation, etc. should be the unique families? 

I will change to the former for the moment, but it's practical to reorganize to the latter, or whatever else.

**Comment by uliska** [comment]
I haven't thought that through, but I think the approach you suggest in the code example looks right. I'd say you can go that way, then we'll see if can keep it.

**Comment by jefferyshivers** [comment]
Prefix field works well so far, so I might commit this separately since the `Styles` field is a little trickier (because whatever they are changed to, the styles each wrap their respective arguments (measure, beat, etc.)). I actually previously tried to make the styles keys this way in the earlier stages, and had to move on b/c it wasn't working out, but this is the stage where I think that can be a priority now.

**Comment by jefferyshivers** [comment]
{annStyles} is a configurable key family now. My solution for applying multiple styles to an argument (and I think a slightly more friendly approach than the previous one, for which the syntax was
`\...{style-level-3 {style-level-2 {style-level-1 {##1}}}}`, where `##1` had to be included when the commands were used) is like:

```
\setkeys{annStyles}{%
    message={\uppercase},% goes to \annMessage
    message-2nd={\textit},% goes to \annMessageO (abbreviation of annMessageOuter)
    message-3rd={\color{cyan}}% goes to \annMessageOO
}
```

which will be applied to the message, which is pre-wrapped..
`{\annMessageOO{\annMessageO{\annMessage\lymessage}}}`,
like:
`{\color{cyan}{\textit{\uppercase*message*}}}`.

We might later look at this as a reason to reconfigure keys families to {annMessage}, {annType}, etc. But for the time being this seems to work.
