### ISSUE TITLE
editorial functions don't handle "item" correctly

### ISSUE THREAD

**Issue by uliska** [openlilylib/scholarly#36]
``` lilypond
{
  \editorialAddition NoteHead
  \tempo "Allegro"
  c'
}
```

demonstrates a problem with the approach implemented in #33: The to-be-applied function is looked up using the `item` argument but that function is applied to whatever comes next in the input (because the `mus` argument just consumes the next expression).

I'm not really clear about what to do about it, but I have the impression we need some more complexity in our approach.Maybe it would help to "apply" the annotation "types" through a new, to-b-written music-function and let the choice of actual unction Bis m. 49.

**Comment by jefferyshivers** [comment]
Doesn't this example contradict the logical syntax of an editorial function though? `\tempo ..` shouldn't follow the hook if it isn't the object being edited. Why wouldn't we just do

```
{
  \tempo "Allegro"
  \editorialAddition NoteHead c'
}
```

where `item` and `mus` follow the hook?

> Maybe it would help to "apply" the annotation "types" through a new, to-b-written music-function and let the choice of actual unction Bis m. 49.

I can't really make sense of this.

**Comment by uliska** [comment]
> Doesn't this example contradict the logical syntax of an editorial function though?

Probably you're right, so disregard this comment.

My second paragraph was obviously the victim of a touchpad glitch while posting. But the idea behind it is nonsense as well, as `\editorialAddition` _is_ already the function I wanted to suggest.

However, I think I _do_ have to investigate some mroe with annotations where you'd have to use the tweaking (vs. overriding) syntax.

Still I think the functions should explicitly be applied to the correct grob type. While you're right that my example was indeed conceptually wrong we should somehow respond to such wrong user input instead of only applying the (presumably wrong) function to something we shouldn't..
