### ISSUE TITLE
[draft] and [final] mode in scholarly.sty

### ISSUE THREAD

**Issue by jefferyshivers** [openlilylib/scholarly#7]
### What are the required or desired characteristics (format and style) of annotations in draft mode?

Presumably, draft mode will override any user-defined commands to be a relatively generic, proofread-friendly list.

**Comment by jefferyshivers** [comment]
Indicate missing items in draft mode.

**Comment by uliska** [comment]
I'm not so sure it's the ideal approach to override the user's definitions. My (non-mandatory) suggestion would be to provide two sets of commands for `draft` and `final` and provide the tools to override them individually. A user may well have specific ideas about the final layout but simply take what is suggested for draft. But they may equally want to customize the draft layout.

"relatively generic, proofread-friendly list" is a good description. Two comments: in draft mode it's not necessary to save space, so things can be laid out rather generously (improving readability). It may be a good idea to explicitly write out the labels (while in final mode they are usually hidden. For an example of _my_ idea refer to this [blog post](http://lilypondblog.org/2013/12/using-latex-for-a-musical-edition/)

In any case, it's important to properly handle missing "fields" in the output.

**Comment by jefferyshivers** [comment]
This is referenced in 'formatting / styling' issue as well now.

Perhaps there should be a command/option to `keep final styles` while switching to draft mode, or a default _relatively generic.._ if `keep final styles` is not specified by the user, the generic replacement is assumed. In addition, the user could specify their own `custom draft mode` (in which they might want things such as all caps, larger font, etc.) to replace the generic default in any way. But still be able to override that by `keep final styles`.

**Comment by jefferyshivers** [comment]
There are now unique default styles (that aren't actually _set in stone_) for both `final` and `draft` modes, and options to override each of those (`\setcustomdraft{ the custom settings }` and `\setcustomfinal{ the custom settings }`), with `\usecustomdraft` and `\usecustomfinal` (which only affect their respective modes, so that custom mode styles can be left _active_ while switching to (but not influencing) the other mode). `\finaltodraft` imports the custom final styles to override both default and custom draft modes if desired.

So at this point, the only automatic difference between the two modes is stacked vs. inline arguments. Will likely make those defaults overridable as well.

**Comment by jefferyshivers** [comment]
Do you have thoughts about what the default `[nocustom]` settings should be? Since it's technically optional on _our_ end what the override affects, that of course leaves us with a lot of room. But because so many things are now set through `\setkeys`, all default behaviors will have to be explicitly set, which means many lines just to establish this in the package. Let me know if it isn't clear what that means, but I think this should itself be written in a separate document to keep the main document size minimal.
I suggest the name `default-stylesheet.inp`, or something similar.

**Comment by uliska** [comment]
I only _think_ I fully understand that.
_If_ I do then using an include file for the defaults seems sensible and would also be usable for documentation purposes ("see `default-stylesheet.inp` for the properties that can be overridden").

Regarding the default settings themselves I don't have a very strong opinion, but they should be as simple and unintrusive as possible. `final` should be a concise inline style layout with one paragraph/item per annotation, `draft` maybe the most simple tabular/tabbing structure providing a label/content row per property.

**Comment by jefferyshivers** [comment]
Okay thanks, yes that's what meant.

Follow-up logistical question: should that be in the same folder as `scholarLY.sty`, or subdirectory?

**Comment by uliska** [comment]
I think I'd put it in the same directory to start with. This directory won't be that big anyway.

OTOH I'm not so sure what will happen when the package is incorporated in distros like texlive, so maybe _this_ might suggest different organization. I think I'll ask on the tex-live mailing list what they suggest.

**Comment by uliska** [comment]
Request on the tex-live mailing list turned out to put everything in one directory if possible at all. That's what CTAN requests, and the distro maintainers will take care of putting everything in place in their architecture. See [this thread](http://tug.org/pipermail/tex-live/2016-June/038927.html) and especially [the first reply](http://tug.org/pipermail/tex-live/2016-June/038932.html)

**Comment by jefferyshivers** [comment]
It occurred to me to just use the word "default" as the option handle for default modes. I can change back to "nocustom" if it makes sense that way. And actually, hopefully when the community test drives it, they'll  voice opinions about that if necessary.

> Request on the tex-live mailing list turned out to put everything in one directory if possible at all. That's what CTAN requests, and the distro maintainers will take care of putting everything in place in their architecture.

I actually went ahead and checked earlier in the day and found your thread there - so thanks for looking into that. Just updated the package with that, and the option to use it. If you have tweaks to add to it, please go ahead and do so. And that just as well may be something the user group can comment on as well.

**Comment by jefferyshivers** [comment]
I'm not totally confident in how the input is handled (`scholarLY.sty` line 101). It is as `\input{../default-stylesheet.inp}`, even though the stylesheet is in the same directory as the package. Does that make sense? Just `\input{default-stylesheet.inp}` does not pick up the file.

**Comment by uliska** [comment]
That's strange indeed. What about `\input{./default-stylesheet.inp}`? I would have expected _this_ to refer to the current directory.

**Comment by jefferyshivers** [comment]
No, only `../` worked.

I think that, even though the document is in the same directory as `scholarLY.sty`, latex doesn't know to look there; presumably the _current_ directory is actually still `annotate.tex`'s directory at that point. And `latex-package` was not in tex's search path (well, for me at least). But now it is (5a9531a590263b68d96819a955ada7deeb874e86). _EDIT: correction, now it is in `annotate.tex`'s search path._

This shouldn't be an issue when it exists in the actual tex tree via whatever distribution.
